### ISSUE TITLE
Worker crashes if database connection is lost

### ISSUE THREAD

**Issue by pvdvreede** [chanks/que#130]
Hi, we are doing some testing with Que to make sure that it will be resilient if the database disappears and then reappears.

We are using the Sequel gem for the connection pool and have found that our app will crash out if we kill the database with (ignore the `web_1` which is from docker-compose):

```
web_1 | /usr/local/lib/ruby/gems/2.2.0/gems/sequel-4.27.0/lib/sequel/adapters/postgres.rb:241:in `initialize': PG::ConnectionBad: timeout expired (Sequel::DatabaseConnectionError)
web_1 |         from /usr/local/lib/ruby/gems/2.2.0/gems/sequel-4.27.0/lib/sequel/adapters/postgres.rb:241:in `new'
web_1 |         from /usr/local/lib/ruby/gems/2.2.0/gems/sequel-4.27.0/lib/sequel/adapters/postgres.rb:241:in `connect'
web_1 |         from /usr/local/lib/ruby/gems/2.2.0/gems/sequel-4.27.0/lib/sequel/connection_pool.rb:101:in `make_new'
web_1 |         from /usr/local/lib/ruby/gems/2.2.0/gems/sequel-4.27.0/lib/sequel/connection_pool/threaded.rb:222:in `make_new'
web_1 |         from /usr/local/lib/ruby/gems/2.2.0/gems/sequel-4.27.0/lib/sequel/connection_pool/threaded.rb:195:in `available'
web_1 |         from /usr/local/lib/ruby/gems/2.2.0/gems/sequel-4.27.0/lib/sequel/connection_pool/threaded.rb:131:in `_acquire'
web_1 |         from /usr/local/lib/ruby/gems/2.2.0/gems/sequel-4.27.0/lib/sequel/connection_pool/threaded.rb:145:in `block in acquire'
web_1 |         from /usr/local/lib/ruby/gems/2.2.0/gems/sequel-4.27.0/lib/sequel/connection_pool/threaded.rb:263:in `block in sync'
web_1 |         from /usr/local/lib/ruby/gems/2.2.0/gems/sequel-4.27.0/lib/sequel/connection_pool/threaded.rb:263:in `synchronize'
web_1 |         from /usr/local/lib/ruby/gems/2.2.0/gems/sequel-4.27.0/lib/sequel/connection_pool/threaded.rb:263:in `sync'
web_1 |         from /usr/local/lib/ruby/gems/2.2.0/gems/sequel-4.27.0/lib/sequel/connection_pool/threaded.rb:144:in `acquire'
web_1 |         from /usr/local/lib/ruby/gems/2.2.0/gems/sequel-4.27.0/lib/sequel/extensions/connection_validator.rb:86:in `acquire'
web_1 |         from /usr/local/lib/ruby/gems/2.2.0/gems/sequel-4.27.0/lib/sequel/connection_pool/threaded.rb:102:in `hold'
web_1 |         from /usr/local/lib/ruby/gems/2.2.0/gems/sequel-4.27.0/lib/sequel/database/connecting.rb:249:in `synchronize'
web_1 |         from /usr/local/lib/ruby/gems/2.2.0/gems/que-0.11.2/lib/que/adapters/sequel.rb:10:in `checkout'
web_1 |         from /usr/local/lib/ruby/gems/2.2.0/gems/que-0.11.2/lib/que/job.rb:83:in `work'
web_1 |         from /usr/local/lib/ruby/gems/2.2.0/gems/que-0.11.2/lib/que/worker.rb:78:in `block in work_loop'
web_1 |         from /usr/local/lib/ruby/gems/2.2.0/gems/que-0.11.2/lib/que/worker.rb:73:in `loop'
web_1 |         from /usr/local/lib/ruby/gems/2.2.0/gems/que-0.11.2/lib/que/worker.rb:73:in `work_loop'
web_1 |         from /usr/local/lib/ruby/gems/2.2.0/gems/que-0.11.2/lib/que/worker.rb:17:in `block in initialize'
```

It seems the call at https://github.com/chanks/que/blob/master/lib/que/job.rb#L83 to `checkout` on the adapter does not rescue any exceptions, and this is where it crashes with a PG time out exception.

We are wondering where the best place is to catch this. In the `Job` class on the `work` call, or in the `work_loop`?

**Comment by chanks** [comment]
So I'm guessing that this kills the worker thread, which then kills the
whole process because abort_on_exception is set to true.

I'm actually not sure that this error should be caught, though. I think
that if the database is unavailable it's reasonable for the process to fail
(thereby triggering whatever monitoring system you have in place to both
restart it and notify you), rather than spinning its wheels indefinitely
until the DB reappears.

I may be wrong, though - curious to hear what other people think.

**Comment by pvdvreede** [comment]
Correct, the whole app dies on this issue.

Maybe it is something that will be different in different cases. If we know the db is undergoing maintenance or there are network issues, I would rather that our app self-heals.

Is there a public API to start the workers manually in our code rather than just setting `Que.mode = :async`? That way we can catch this exception ourselves and restart the works. We are also running a rack app in the same process so we cant just use the Que binary...

**Comment by tpitale** [comment]
I, for one, would love for it to crash, at which point upstart or monit or something else would restart the process. But, that being said, I'm using que in production as its own process, and not part of a running rails app.

**Comment by tpitale** [comment]
I commented on what I see using connection_pool in #142 when postgresql is restarted.

**Comment by tpitale** [comment]
So, I've switched to using pond, which let's me remove a closed connection from the pool. Handy.

**Comment by texpert** [comment]
The whole stack of apps goes down, and it wouldn't help restarting -  the DB is located on another server.

Would be great to have this behaviour configurable - to rescue the lost connection or not.
