### ISSUE TITLE
PG::UndefinedTable error when running migration

### ISSUE THREAD

**Issue by guillewu** [chanks/que#137]
I'm following the instructions, and when running `rake db:migrate` I get:
```
rake aborted!
PG::UndefinedTable: ERROR:  relation "que_jobs" does not exist
LINE 9:       FROM que_jobs
```

Am I missing something?

Thanks

**Comment by joevandyk** [comment]
What does `rake db:migrate --trace` show?

**Comment by guillewu** [comment]
```
rake aborted!
PG::UndefinedTable: ERROR:  relation "que_jobs" does not exist
LINE 9:       FROM que_jobs
                   ^
/Users/guillewu/.rvm/gems/ruby-2.2.3/gems/que-0.11.2/lib/que/adapters/base.rb:74:in `prepare'
/Users/guillewu/.rvm/gems/ruby-2.2.3/gems/que-0.11.2/lib/que/adapters/base.rb:74:in `block in execute_prepared'
/Users/guillewu/.rvm/gems/ruby-2.2.3/gems/que-0.11.2/lib/que/adapters/active_record.rb:5:in `block in checkout'
/Users/guillewu/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/Users/guillewu/.rvm/gems/ruby-2.2.3/gems/que-0.11.2/lib/que/adapters/active_record.rb:48:in `checkout_activerecord_adapter'
/Users/guillewu/.rvm/gems/ruby-2.2.3/gems/que-0.11.2/lib/que/adapters/active_record.rb:5:in `checkout'
/Users/guillewu/.rvm/gems/ruby-2.2.3/gems/que-0.11.2/lib/que/adapters/base.rb:65:in `execute_prepared'
/Users/guillewu/.rvm/gems/ruby-2.2.3/gems/que-0.11.2/lib/que/adapters/base.rb:48:in `execute'
/Users/guillewu/.rvm/gems/ruby-2.2.3/gems/que-0.11.2/lib/que.rb:73:in `execute'
/Users/guillewu/.rvm/gems/ruby-2.2.3/gems/que-0.11.2/lib/que.rb:81:in `job_stats'
/Users/guillewu/Development/web/config/initializers/check_for_active_workers_job.rb:3:in `<top (required)>'
/Users/guillewu/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `load'
/Users/guillewu/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `block in load'
/Users/guillewu/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/guillewu/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `load'
/Users/guillewu/.rvm/gems/ruby-2.2.3/gems/railties-4.2.4/lib/rails/engine.rb:652:in `block in load_config_initializer'
/Users/guillewu/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/notifications.rb:166:in `instrument'
/Users/guillewu/.rvm/gems/ruby-2.2.3/gems/railties-4.2.4/lib/rails/engine.rb:651:in `load_config_initializer'
/Users/guillewu/.rvm/gems/ruby-2.2.3/gems/railties-4.2.4/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
/Users/guillewu/.rvm/gems/ruby-2.2.3/gems/railties-4.2.4/lib/rails/engine.rb:615:in `each'
/Users/guillewu/.rvm/gems/ruby-2.2.3/gems/railties-4.2.4/lib/rails/engine.rb:615:in `block in <class:Engine>'
/Users/guillewu/.rvm/gems/ruby-2.2.3/gems/railties-4.2.4/lib/rails/initializable.rb:30:in `instance_exec'
/Users/guillewu/.rvm/gems/ruby-2.2.3/gems/railties-4.2.4/lib/rails/initializable.rb:30:in `run'
/Users/guillewu/.rvm/gems/ruby-2.2.3/gems/railties-4.2.4/lib/rails/initializable.rb:55:in `block in run_initializers'
/Users/guillewu/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
/Users/guillewu/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
/Users/guillewu/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:420:in `block (2 levels) in each_strongly_connected_component_from'
/Users/guillewu/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
/Users/guillewu/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:419:in `block in each_strongly_connected_component_from'
/Users/guillewu/.rvm/gems/ruby-2.2.3/gems/railties-4.2.4/lib/rails/initializable.rb:44:in `each'
/Users/guillewu/.rvm/gems/ruby-2.2.3/gems/railties-4.2.4/lib/rails/initializable.rb:44:in `tsort_each_child'
/Users/guillewu/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:413:in `call'
/Users/guillewu/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:413:in `each_strongly_connected_component_from'
/Users/guillewu/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
/Users/guillewu/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:345:in `each'
/Users/guillewu/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:345:in `call'
/Users/guillewu/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
/Users/guillewu/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
/Users/guillewu/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
/Users/guillewu/.rvm/gems/ruby-2.2.3/gems/railties-4.2.4/lib/rails/initializable.rb:54:in `run_initializers'
/Users/guillewu/.rvm/gems/ruby-2.2.3/gems/railties-4.2.4/lib/rails/application.rb:352:in `initialize!'
/Users/guillewu/Development/web/config/environment.rb:5:in `<top (required)>'
/Users/guillewu/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
/Users/guillewu/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
/Users/guillewu/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/guillewu/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
/Users/guillewu/.rvm/gems/ruby-2.2.3/gems/railties-4.2.4/lib/rails/application.rb:328:in `require_environment!'
/Users/guillewu/.rvm/gems/ruby-2.2.3/gems/railties-4.2.4/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/Users/guillewu/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:240:in `call'
/Users/guillewu/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:240:in `block in execute'
/Users/guillewu/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:235:in `each'
/Users/guillewu/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:235:in `execute'
/Users/guillewu/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:179:in `block in invoke_with_call_chain'
/Users/guillewu/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/Users/guillewu/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/Users/guillewu/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:201:in `block in invoke_prerequisites'
/Users/guillewu/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:199:in `each'
/Users/guillewu/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:199:in `invoke_prerequisites'
/Users/guillewu/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:178:in `block in invoke_with_call_chain'
/Users/guillewu/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/Users/guillewu/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/Users/guillewu/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:165:in `invoke'
/Users/guillewu/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:150:in `invoke_task'
/Users/guillewu/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:106:in `block (2 levels) in top_level'
/Users/guillewu/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:106:in `each'
/Users/guillewu/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:106:in `block in top_level'
/Users/guillewu/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:115:in `run_with_threads'
/Users/guillewu/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:100:in `top_level'
/Users/guillewu/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:78:in `block in run'
/Users/guillewu/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/Users/guillewu/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:75:in `run'
/Users/guillewu/.rvm/rubies/ruby-2.2.3/bin/rake:37:in `<main>'
Tasks: TOP => db:migrate => environment
```

**Comment by joevandyk** [comment]
What's on `/Users/guillewu/Development/web/config/initializers/check_for_active_workers_job.rb` on line 3?

**Comment by joevandyk** [comment]
I imagine it's something that expects that `que_jobs` table is already setup, possibly asking for job stats. You could try rescuing the exception on that line so that the rest of the migration process can happen.

**Comment by guillewu** [comment]
@joevandyk Thanks for pointing towards the right direction :+1: ! Closing issue.
