### ISSUE TITLE
uninitialized constant Que::Rails::Railtie

### ISSUE THREAD

**Issue by 9mm** [chanks/que#206]
I'm trying out Que `1.0.0.beta`, when I start it on a new rails app I get this. Ruby 2.5.0 and rails 5.1.5

```
/Users/zesty/.rbenv/versions/2.5.0/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:84:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'que'. (Bundler::GemRequireError)
Gem Load Error is: uninitialized constant Que::Rails::Railtie
Did you mean?  Que::Rails
Backtrace for gem load error is:
/Users/zesty/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/que-1.0.0.beta/lib/que/rails/railtie.rb:5:in `<module:Rails>'
/Users/zesty/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/que-1.0.0.beta/lib/que/rails/railtie.rb:4:in `<module:Que>'
/Users/zesty/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/que-1.0.0.beta/lib/que/rails/railtie.rb:3:in `<top (required)>'
/Users/zesty/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/que-1.0.0.beta/lib/que.rb:115:in `require_relative'
/Users/zesty/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/que-1.0.0.beta/lib/que.rb:115:in `<top (required)>'
/Users/zesty/.rbenv/versions/2.5.0/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:81:in `require'
/Users/zesty/.rbenv/versions/2.5.0/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:81:in `block (2 levels) in require'
/Users/zesty/.rbenv/versions/2.5.0/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:76:in `each'
/Users/zesty/.rbenv/versions/2.5.0/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:76:in `block in require'
/Users/zesty/.rbenv/versions/2.5.0/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:65:in `each'
/Users/zesty/.rbenv/versions/2.5.0/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:65:in `require'
/Users/zesty/.rbenv/versions/2.5.0/lib/ruby/site_ruby/2.5.0/bundler.rb:114:in `require'
/Users/zesty/Code/rentpaid/config/application.rb:16:in `<top (required)>'
/Users/zesty/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.1.5/lib/rails/command/actions.rb:15:in `require'
/Users/zesty/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.1.5/lib/rails/command/actions.rb:15:in `require_application_and_environment!'
/Users/zesty/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.1.5/lib/rails/commands/console/console_command.rb:96:in `perform'
/Users/zesty/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
/Users/zesty/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
/Users/zesty/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
/Users/zesty/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.1.5/lib/rails/command/base.rb:63:in `perform'
/Users/zesty/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.1.5/lib/rails/command.rb:44:in `invoke'
/Users/zesty/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.1.5/lib/rails/commands.rb:16:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Bundler Error Backtrace:
```

**Comment by 9mm** [comment]
Sorry, this was fixed in one of the latest commits. I had to actually pull from GitHub instead of rubygems.

    gem 'que', git: 'git://github.com/chanks/que.git', branch: '1.0'

**Comment by chanks** [comment]
Oh, cool. By the way, I usually like to specify a `ref` when I use a `git` source, to make sure that the dependency doesn't change when I'm not expecting it to.

**Comment by 9mm** [comment]
Thanks for the tip, will do.

Just to make sure I get the migration properly, can I show you my 'before and after' settings and you can tell me if I got everything right?

**BEFORE -- initializers/que.rb**

```
Que.mode = :off
Que.worker_count = 1
Que.wake_interval = 5.0
Que.use_prepared_statements = false # PGBouncer
Que.logger = Logger.new(STDOUT)

Que.log_formatter = proc do |data|
  # exclude :job_unavailable which creates lots of chatter
  JSON.dump(data) unless data[:event] == :job_unavailable
end

Que.error_notifier = proc do |error|
  Raven.capture { raise error }
end
```

**AFTER -- initializers/que.rb**

```
Que.use_prepared_statements = false # PGBouncer
Que.logger = Logger.new(STDOUT)

Que.log_formatter = proc do |data|
  # exclude :job_unavailable which creates lots of chatter
  JSON.dump(data) unless data[:event] == :job_unavailable
end

Que.error_notifier = proc do |error|
  Raven.capture { raise error }
end
```

**BEFORE -- models/que.rb**

```
class QueJob < ActiveRecord::Base
  # https://github.com/chanks/que/blob/master/docs/inspecting_the_queue.md#custom-queries
end
```

**AFTER -- models/que.rb**

Based on the changelog, it seems maybe I don't need this anymore, and I can delete it? But how do I access the AR methods? I tried `Que::Job.where()` and `Que.where()`.

**BEFORE -- que command**

    que ./config/environment.rb

**AFTER -- que command**

Is the command the same? I noticed you removed `worker_count` and `wake_interval` from the config file (which leads me to believe these settings are no longer needed), yet they're still configurable via command line if you use `que -h`, so I'm not sure if I'm supposed to set them still (using the `que` command) or not at all?

**MISC Questions**

* Does `maximum_retry_count` default to 0 retries like the old version of Que?
